name: Build

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  workflow_call:
  pull_request:

env:
  COMPOSER_AUTH: ${{ secrets.COMPOSER_AUTH }}
  EXTENSIONS: pcntl, bcmath, zip, gd, sodium, :php-psr
  PHP_VERSION: "8.2"
  NODE_VERSION: 20

jobs:
  build-lint-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ env.PHP_VERSION }}
        extensions: ${{ env.EXTENSIONS }}
        tools: composer, pecl
        coverage: xdebug

    - name: Install Deps
      uses: "ramsey/composer-install@v3"

    - name: Setup node
      uses: actions/setup-node@v4
      with:
        node-version: ${{ env.NODE_VERSION }}
        cache: "npm"

    - name: Build App
      run: npm ci

    - name: Check Code Styles
      run: "vendor/bin/pint --test"

    - name: Setup problem matchers for PHP
      run: echo "::add-matcher::${{ runner.tool_cache }}/php.json"

    - name: Run PHPStan
      run: vendor/bin/phpstan analyse --no-progress

    - name: Initialize Project
      run: |
        cp .env.example .env
        composer init

    - name: Run PHP Unit Tests
      run: php artisan test --ci --coverage-clover=coverage.xml --log-junit=test-report.xml

    - name: Check Code Styles
      run: "npm run prettier"

    - name: Run ESLint
      run: npm run lint

    - name: Run CDK Tests
      run: npm test
