name: Deploy

concurrency: deployment

on:
  release:
    types: [published]

jobs:
  upload-release:
    runs-on: ubuntu-latest

    steps:

    - name: Set start time
      run: |
        START_TIME=$(date +%s) 
        echo "START_TIME=$START_TIME" >> $GITHUB_ENV

    - name: Checkout code
      uses: actions/checkout@v4

    - name: Zip files
      run: |
        zip -r laravel-app-latest.zip .

    - name: Copy file to S3 with metadata
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.PUBLIC_REPO_AWS_S3_ACCESS_KEY }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.PUBLIC_REPO_AWS_S3_SECRET_KEY }}
        AWS_REGION: us-east-2
      run: |
        aws s3 cp --metadata github-sha=${{ github.sha }},start-time=${START_TIME} ./laravel-app-latest.zip s3://laravel-app-build-bucket-103902666/artifact/laravel-app-latest.zip
