name: Deploy

concurrency: deployment

on:
  release:
    types: [published]

permissions:
  id-token: write   # This is required for requesting the JWT
  contents: read    # This is required for actions/checkout
  pull-requests: write

jobs:
  upload-release:
    runs-on: ubuntu-latest

    steps:

    - name: Set start time
      run: |
        START_TIME=$(date +%s) 
        echo "START_TIME=$START_TIME" >> $GITHUB_ENV

    - name: configure aws credentials
      uses: aws-actions/configure-aws-credentials@v3
      with:
        role-to-assume: arn:aws:iam::192156030346:role/PublicGitHubRepoOIDCRole
        role-session-name: DeployGitHubActions
        aws-region: us-east-2

    - name: Checkout code
      uses: actions/checkout@v4

    - name: Zip files
      run: |
        zip -r laravel-app-latest.zip .

    - name: Copy file to S3 with metadata
      env:
        AWS_REGION: us-east-2
      run: |
        aws s3 cp --metadata github-sha=${{ github.sha }},start-time=${START_TIME} ./laravel-app-latest.zip s3://articles-laravel-continuous-integration/laravel-app-latest.zip
