name: DevCycle Usages

on:
  push:
    branches: [main]

env:
  DVC_PROJECT_KEY: "articles-laravel-continuous-integration"

jobs:
  dvc-code-usages:
    runs-on: ubuntu-latest
    name: DevCycle Feature Flag Code Usages
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: DevCycleHQ/feature-flag-code-usage-action@v1.1.2
        with:
          github-token: ${{ secrets.PUBLIC_REPO_BOT_GITHUB_TOKEN }}
          client-id: ${{ secrets.PUBLIC_DVC_CLIENT_ID }}
          client-secret: ${{ secrets.PUBLIC_DVC_CLIENT_SECRET }}
          project-key: ${{ env.PUBLIC_DVC_PROJECT_KEY }}
