name: Release

on:
  workflow_call:
  pull_request:

env:
  COMPOSER_AUTH: ${{ secrets.COMPOSER_AUTH }}
  EXTENSIONS: pcntl, bcmath, zip, gd, sodium, :php-psr
  PHP_VERSION: "8.2"

jobs:
  php-formatting-and-styling:
    runs-on: ubuntu-latest
    needs: build
    concurrency:
      group: release

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ env.PHP_VERSION }}
          extensions: ${{ env.EXTENSIONS }}
          tools: composer, pecl
          coverage: xdebug

      - name: Install Deps
        uses: "ramsey/composer-install@v3"

      - name: Check Code Styles
        run: "vendor/bin/pint --test"

  node-formatting-and-styling:
    runs-on: ubuntu-latest
    needs: build
    concurrency:
      group: release

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: "npm"

      - name: Build App
        run: npm ci

      - name: Check Code Styles
        run: "npm run prettier"
